### ISSUE TITLE
Remove rbytes

### ISSUE THREAD

**Issue by andyhot** [WarheadsSE/node-gntp#1]
Hi, given that crypto also has a randomBytes method, 
perhaps it's possible to remove usage of rbytes in node_modules/GNTP.js

PS i found it impossible to install rbytes on windows, hence my interest

**Comment by WarheadsSE** [comment]
Agreed, but as this was written on node v0.4.12 which did /not/ have randomBytes in crypto :) totally agree. I plan on making these changes and more as v0.6 comes out stable. The buffer object will also support native hex formatting, so that also removed the need for rbytes' exported toHex() and writeHex() addons to the Buffer object.  I might just make the changes ahead of time and put them into somthing like gntp-v6.js or something.

rbytes cannot be installed on windows because the windows port does not currently support binary extensions (which rbytes is)

Future notes:
rbytes = unneeded in node 0.5+, replace with the newly implemented bits from the Buffer object and Crypto's randomBytes

**Comment by WarheadsSE** [comment]
I have the appropriate changes, but split it into a GNTPv5, and matching gntp-send-v5.js (only the require changed)

They are working on my W7 Pro w/ node.exe reporting process.versions.node = 0.5.9
